CERN/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('user/',include(("users.urls",'users'),namespace='user')),
    path('article/',include(('articles.urls','articles'), namespace='article')),
    path('announcement/',include(('announcement.urls','announcement'),namespace='announcement')),
    path('meeting/',include(('meeting_reports.urls','meeting_reports'), namespace='meeting-reports')),
    path('shift/',include(('shifts.urls','shifts'), namespace='shift')),
    path('main/',include(('main.urls','main'), namespace='main')),
    path('research/',include(('researchs.urls','researchs'), namespace='research')),
    path('search/', include(('search.urls','search'), namespace='search')),
    path('gallery/', include(('gallery.urls','gallery'), namespace='gallery')),
    path('news/', include(('news.urls','news'), namespace='news')),
    path('projects/', include(('projects.urls','projects'), namespace='projects')),
    path('documents/', include(('documents.urls','documents'), namespace='documents')),
    path('sss/', include(('sss.urls','sss'), namespace='sss'))
]
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATICFILES_DIRS)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

meeting_reports/urls.py
from django.contrib import admin
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('add/',views.add, name='add'),
    path('detail/<int:id>',views.detail, name='detail'),
    path('add-category/',views.add_change_delete_category, name="add-category"),
    path('update-category/<int:pk>',views.update_category, name='update-category'),
    path('meeting-list/',views.meeting_list, name='meeting-list'),
    path('meeting-list/add',views.add_meeting_list, name='add-meeting-list'),
    path('meeting-detail/<int:pk>',views.meeting_detail, name='meeting-detail'),
]

sss/urls.py
from django.urls import path
from . import views

urlpatterns = [
    
    path('', views.index, name='index')
]

meeting_reports/models.py
from django.db import models
from django.urls import reverse
# Create your models here.

class MeetingReportCategory(models.Model):
    #meeting = models.ForeignKey(MeetingReport, on_delete=models.SET_NULL)
    category_name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return f'{self.category_name}'

class MeetingReport(models.Model):
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE, related_name = 'metting_reports')
    title = models.CharField(max_length=255)
    description = models.TextField()
    file = models.FileField(upload_to='meeting_reports')
    category = models.ManyToManyField(MeetingReportCategory, related_name='categories', blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    date = models.DateField()

    class Meta:
        ordering= ['-date']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("meeting-reports:detail", kwargs={"id": self.id})


class Meeting(models.Model):
    user = models.ForeignKey('auth.User', on_delete = models.CASCADE, related_name='meetings')
    title = models.CharField(max_length=255)
    description = models.TextField()
    url = models.URLField(max_length=255, blank=True, null=True)
    file = models.FileField(upload_to='meeting', null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    date = models.DateField()
    
    def __str__(self):
        return self.title

    

meeting_reports/forms.py
from django.forms.widgets import CheckboxSelectMultiple
from .models import MeetingReport, Meeting
from django import forms


class MeetingReportForm(forms.ModelForm):
    """
    category = forms.ModelMultipleChoiceField(
        queryset=MeetingReportCategory.objects.all(),
        widget = forms.CheckboxSelectMultiple,
    )
    """
    class Meta:
        model = MeetingReport
        exclude = ['user', 'created_at']

    def __init__(self, *args, **kwargs):
        super(MeetingReportForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            if field == 'file':
                continue
            self.fields[field].widget.attrs = {'class':'form-control'}


class MeetingForm(forms.ModelForm):

    class Meta:
        model = Meeting
        exclude = ['user', 'created_at']
        

meeting_reports/views.py
from django.core import paginator
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.http import JsonResponse
from .models import MeetingReport, MeetingReportCategory, Meeting
from .forms import MeetingReportForm, MeetingForm
from django.contrib.auth.decorators import login_required
from django.core.paginator import  Paginator, EmptyPage, PageNotAnInteger

# Create your views here.
def index(request):
    reports = MeetingReport.objects.all()

    page = request.GET.get('page',1)

    paginator = Paginator(reports,1)

    try:
        reports = paginator.page(page)
    except PageNotAnInteger:
        reports = paginator.page(1)
    except EmptyPage:
        reports = paginator.page(paginator.num_pages)
    context = {
        'reports':reports,
        'nbar' : 'list-reports',
    }

    return render(request, 'meeting/meeting_reports.html', context)

@login_required(login_url="user:login")
def add(request):
    categories = MeetingReportCategory.objects.all()
    form = MeetingReportForm(request.POST or None, request.FILES or None)

    nbar = "add-report"
    context = {'categories':categories,'form':form,'nbar':nbar}
    if form.is_valid():

        created_meeting = form.save(commit=False)
        created_meeting.user = request.user
        created_meeting.save()
        created_meeting.category.set(request.POST.getlist('category'))
        created_meeting.save()

    print(form.errors)
    return render(request,'meeting/meeting_reports_add.html', context)

def detail(request, id):
    report = get_object_or_404(MeetingReport, id=id)

    return render(request, 'meeting/meeting_reports_detail.html',{'report':report})


def add_change_delete_category(request):
    categories = MeetingReportCategory.objects.all()
    context = {
        'nbar': 'add-category',
        'categories':categories,
        'delete_category': None,
    }
    if request.method == 'POST':
        if request.is_ajax():
            category_name = request.POST.get('category_name')

            if MeetingReportCategory.objects.filter(category_name=category_name).exists():

                return JsonResponse({'success':False,'message':'Aynı Kategori Zaten Mevcut'}, status=400)

            MeetingReportCategory.objects.create(category_name=category_name)

            return JsonResponse({'success':True,'message':'Kategori Başarıyla Oluşturuldu'}, status=200)

        if request.POST.get('delete'):
            category = MeetingReportCategory.objects.get(id=request.POST.get('category_id'))
            category.delete()
            
            context.update({
                'delete_category':True,
                'deleted_category_name':category.category_name,
            })
            return render(request,'meeting/add_category.html', context)

    return render(request, 'meeting/add_category.html', context)

def update_category(request, pk):
    category = get_object_or_404(MeetingReportCategory, id=pk)

    if request.method == 'POST':
        category_name = request.POST.get('category_name')
        if MeetingReportCategory.objects.filter(category_name=category_name).exists():
            return JsonResponse({'success':False,'message':'Aynı Kategori Zaten Mevcut'}, status=400)

        category.category_name = category_name
        category.save()

        return JsonResponse({'success':True,'message':'Kategori Başarıyla Güncellendi.'}, status=200) 

    return render(request, 'meeting/update_category.html',{'category':category})


def meeting_list(request):
    meeting_lists = Meeting.objects.all()

    page = request.GET.get('page',1)

    paginator = Paginator(meeting_lists, 10)

    try:
        meeting_lists = paginator.page(page)
    except PageNotAnInteger:
        meeting_lists = paginator.page(1)
    except EmptyPage:
        meeting_lists = paginator.page(paginator.num_pages)

    context = {
        'meeting_lists' : meeting_lists,
    }
    return render(request, 'meeting/meeting_list.html', context)

def add_meeting_list(request):
    form = MeetingForm(request.POST or None, request.FILES or None)

    context = {
        'form' : form,
    }

    if form.is_valid():
        created_meeting = form.save(commit=False)
        created_meeting.user = request.user
        created_meeting.save()

        return redirect('meeting-reports:meeting-list')

    return render(request, 'meeting/add_meeting_list.html',context)

def meeting_detail(request, pk):
    meeting = get_object_or_404(Meeting, id=pk)

    return render(request, 'meeting/meeting_detail.html',{'meeting':meeting})

templates/meeting/add_category.html
{% extends 'base/base.html' %}
{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
    <h2>{% translate 'Kategori Ekle' %}</h2>
    <hr>
{% endblock title %}


{% block content %}


<div class="row">
<div class="col-3">
    <form method="POST" id="create_form">

        {% csrf_token %}
        <div class="form-group">
            <label>{% translate 'Kategori Adı' %} : </label><input type="text" placeholder="Kategori Adı" class="form-control" name="category_name" id="id_category_name">
        </div>
        
        <input type="submit" name="create" class="ui inverted green button" value="{% translate 'Oluştur' %}"/>
    
    </form>
</div>
<div class="col-2"></div>
<div class="col-7 float-right" >
    <div style="width: 100%; height: 500px; overflow-y: scroll; margin-bottom: 10px;border:1px inset lightgray;padding: 5px;">
        {% for category in categories %}
        
        <form method="POST">
            {% csrf_token %}
            <div class="form-group">
                <div class="ui middle aligned divided list">
                    <div class="item">
                    <div class="right floated content">
                            <input type="submit" name="delete" class="ui button red" value="Delete" />
                            <input type="hidden" name="category_id" value="{{category.id}}" />
                        
                        <a href="{% url 'meeting-reports:update-category' category.id %}" class="ui button teal update-box">Update</a>
                    </div>
                    <img class="ui avatar image" src="{% static 'images/atom.png' %}">
                    <div class="content">
                        {{category.category_name}}
                    </div>
                    </div>
                </div>
            </div>
        </form>
        {% endfor %}
        </div>
    </div>
</div>
<script>
    $(document).ready(function() {
        $(".update-box").fancybox({
            openEffect: 'elastic',
            closeEffect: 'elastic',
            autoSize: true,
            type: 'iframe',
            iframe: {
                preload: false // fixes issue with iframe and IE
            }
        });
    });

    $(document).ready(function(){
        $('#create_form').submit(function(e){
          e.preventDefault()
          var serializedData = $(this).serialize()
          
          $.ajax({
            type:'POST',
            url:'/meeting/add-category/',
            data: serializedData,
            success: function(response){
              Swal.fire("Başarılı","Kategori Oluşturuldu","success")
            },
            error: function(response){
              Swal.fire("Hata",`${response.responseJSON.message}`,"error")
            }
          })
        })
      })
      
</script>

{% if delete_category %}
<script>
    Swal.fire('Category Silindi', '{{deleted_category_name}} isimli kategori silindi','info')
</script>
{% endif %}
{% endblock %}

{% block lastarticles %}

{% endblock %}

templates/meeting/add_meeting_list.html
{% extends 'base/base.html' %}

{% block title %}
    <h3>Toplantı Listesi Ekle</h3>
    <hr>
{% endblock %}

{% block content %}
<form method="POST" class="ui form" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
        <label>Başlık</label> 
        <input type="text" name="title" class="form-control" />
    </div>

    <div class="form-group">
        <label>Açıklama</label> 
        <textarea name="description" class="form-control">

        </textarea>
    </div>

    <div class="form-group">
        <label>Dosya</label> 
        <input type="file" name="file" class="form-control-file" />
    </div>

    <div class="form-group">
        <label>URL</label> 
        <input type="text" name="url" class="form-control" placeholder="Google Docs URL"/>
    </div>

    <div class="form-group">
        <label>Tarih</label> 
        <input type="date" name="date" class="form-control" />
    </div>
    
    <input type="submit" class="ui button green" value="Ekle" />
</form>
{% endblock %}

{% block lastarticles %}

{% endblock %}

templates/meeting/meeting_detail.html
{% extends 'base/base.html' %}

{% block title %}
    <h3>{{meeting.title}}</h3>
    <hr>
{% endblock %}

{% block content %}
    

    <div class="article-content mb-5">
        <p>{{meeting.description|safe}}</p>
        {% if meeting.file %}
        <a href="{{meeting.file.url}}" class="big ui inverted blue button">İndir <i class="fas fa-file-download"></i></a>
        {% endif %}
        {% if meeting.url %}
        <!--<iframe class="mt-5" height="800px" width="100%" src="{{meeting.url}}"></iframe>-->

        <a class="ui button primary big gallerypdf" data-fancybox-type="iframe" href="{{meeting.url}}">Görüntüle</a>

        <script>
            $(document).ready(function() {
                $(".gallerypdf").fancybox({
                    openEffect: 'elastic',
                    closeEffect: 'elastic',
                    autoSize: true,
                    type: 'iframe',
                    iframe: {
                        preload: false // fixes issue with iframe and IE
                    }
                });
            });
        </script>
        {% endif %}
        <hr style="background:lightgray;">
        
        
    </div>
{% endblock %}

templates/meeting/meeting_list.html
{% extends 'base/base.html' %}

{% block title %}
    <div class="row" style="align-items: baseline; width:100%;">
        <div class="">
            <h3>Tablolar</h3>
        </div>
        {% if request.user.is_staff or request.user.is_superuser %}
        <div class="ml-5">
            <a href="{% url 'meeting-reports:add-meeting-list' %}" class="ui button blue">Liste Ekle</a>
        </div>
        {% endif %}
    </div>
    
    <hr>
{% endblock %}

{% block content %}
{% for item in meeting_lists %}
    <div class="ui card" style="width:100%;">
        <div class="content">
        <div class="header">{{item.title}}</div>
        </div>
        <div class="content">
        <h4 class="ui sub header">{{item.date}}</h4>
        <div class="ui small feed">
            <div class="event">
            <div class="content">
                <div class="summary">
                {{item.description|safe|truncatewords:30}}
                </div>
            </div>
            </div>
        </div>
        </div>
        <div class="extra content" align="center">
        <a href="{% url 'meeting-reports:meeting-detail' item.id %}" class="ui inverted blue button">Görüntüle</a>
        </div>
  </div>
{% endfor %}

{% if meeting_lists.has_other_pages %}
  <ul class="pagination">
    {% if meeting_lists.has_previous %}
      <li><a href="?page={{ meeting_lists.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in meeting_lists.paginator.page_range %}
      {% if meeting_lists.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if meeting_lists.has_next %}
      <li><a href="?page={{ meeting_lists.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}

{% endblock %}

templates/meeting/meeting_reports.html
{% extends 'base/base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}
    <h2>{% translate 'Toplantı Raporları' %}</h2>
    <hr>
{% endblock title %}


{% block content %}
<div id="pagination-div">
    {% include 'meeting/partial/partial-list.html' %}
</div>

{% endblock %}

templates/meeting/meeting_reports_add.html
{% extends 'base/base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}
    <h2>{% translate 'Toplantı Raporları Ekle' %}</h2>
    <hr>
{% endblock title %}


{% block content %}

<form method="POST" enctype="multipart/form-data">

    {% csrf_token %}
    <div class="form-group">
        <label>{% translate 'Başlık' %} : </label><input type="text" placeholder="Başlık" class="form-control" name="title" id="id_title">
    </div>
    <div class="form-group">
        <label>{% translate 'Açıklama' %} : </label><textarea  placeholder="Açıklama" class="form-control" name="description" id = "id_description"></textarea>
    </div>
    <div class="form-group">
        <label>{% translate 'Dosya' %} <small style="color:red;">(Lütfen PDF Formatında Dosya Yükleyiniz !)</small> : </label><input type="file" placeholder="Başlık" name="file" id="id_file">
    </div>
    <div class="form-group">
        <label>{% translate 'Kategori' %} : </label>
        <select class="js-example-basic-multiple form-control" name="category" multiple="multiple">
            {% for category in categories %}
            <option value="{{category.id}}" data-icon="fa-plus">{{category.category_name}}</option>
            {% endfor %}
        </select>
    </div>
    <div class="form-group">
        <label>{% translate 'Toplantı Tarihi' %} : </label><input type="date" placeholder="Başlık" class="form-control" name="date" id="id_date">
    </div>
    <button class="ui inverted green button">{% translate 'Yayınla' %}</button>

</form>

{% endblock %}

templates/meeting/meeting_reports_detail.html
{% extends 'base/base.html' %}

{% block title %}
    <h2>{{report.title}}</h2>
    <small>Yazar : {{report.user.username}}</small>
    <hr style="background-color:lightgray;">
{% endblock %}

{% block content %}
    <div class="article-content mb-5">
    <p>{{report.description|safe}}</p>
    
    <div align="center">
        <a class="ui button massive gallerypdf" data-fancybox-type="iframe" href="{{report.file.url}}">Görüntüle</a>
    </div>
    
        
    <!--<embed src="{{report.file.url}}#toolbar=1&navpages=0&scrollbar=0&statusbar=0&view=Fit" type="application/pdf" width="100%" height="600px" />-->
    </div>
    <hr style="background:lightgray;">

    

    <script>
        $(document).ready(function() {
            $(".gallerypdf").fancybox({
                openEffect: 'elastic',
                closeEffect: 'elastic',
                autoSize: true,
                type: 'iframe',
                iframe: {
                    preload: false // fixes issue with iframe and IE
                }
            });
        });
    </script>
    
{% endblock %}

templates/meeting/update_category.html
{% extends 'base/base.html' %}

{% block sidebar %}
<div class="container mt-5" align="center">
    <form method="POST" id="create_form">
        {% csrf_token %}
        <div class="ui huge form">
            <div class="field">
            <label>Kategori Adı</label>
            <input placeholder="Kategori Adı" type="text" name="category_name" value="{{category.category_name}}">
            </div>
            <input type="submit" class="ui green button" value="Kaydet" />
        </div>

    </form>
</div>

<script>
    $(document).ready(function(){
        $('#create_form').submit(function(e){
          e.preventDefault()
          var serializedData = $(this).serialize()
          
          $.ajax({
            type:'POST',
            url:'/meeting/update-category/{{category.id}}',
            data: serializedData,
            success: function(response){
              Swal.fire("Başarılı","Kategori Güncellendi.","success")
            },
            error: function(response){
              Swal.fire("Hata",`${response.responseJSON.message}`,"error")
            }
          })
        })
      })
</script>
{% endblock %}
{% block title %}

{% endblock %}

{% block content %}

    
{% endblock %}

{% block lastarticles %}

{% endblock %}