CERN/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('user/',include(("users.urls",'users'),namespace='user')),
    path('article/',include(('articles.urls','articles'), namespace='article')),
    path('announcement/',include(('announcement.urls','announcement'),namespace='announcement')),
    path('meeting/',include(('meeting_reports.urls','meeting_reports'), namespace='meeting-reports')),
    path('shift/',include(('shifts.urls','shifts'), namespace='shift')),
    path('main/',include(('main.urls','main'), namespace='main')),
    path('research/',include(('researchs.urls','researchs'), namespace='research')),
    path('search/', include(('search.urls','search'), namespace='search')),
    path('gallery/', include(('gallery.urls','gallery'), namespace='gallery')),
    path('news/', include(('news.urls','news'), namespace='news')),
    path('projects/', include(('projects.urls','projects'), namespace='projects')),
    path('documents/', include(('documents.urls','documents'), namespace='documents')),
    path('sss/', include(('sss.urls','sss'), namespace='sss'))
]
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATICFILES_DIRS)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

researchs/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('create/', views.create, name='create'),
    path('list/',views.list, name='list'),
    path('show/<str:slug>/',views.show,name='show'),
    path('create-category/',views.create_category, name='create-category'),
    path('get-categories-ajax/',views.get_categories,name='get-categories-ajax'),
]

sss/urls.py
from django.urls import path
from . import views

urlpatterns = [
    
    path('', views.index, name='index')
]

researchs/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.utils.text import slugify
from django.urls import reverse

class CategoryResearch(models.Model):
    category_name = models.CharField(max_length=50)

    def __str__(self):
        return self.category_name

    class Meta:
        ordering = ['category_name']

class ResearchManager(models.Manager):
    def get_three_items(self, *args, **kwargs):
        return super(ResearchManager, self).all()[:3]

class Research(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField()
    content = RichTextField()
    category = models.ForeignKey(CategoryResearch, on_delete=models.SET_NULL, null=True, related_name='researchs')
    slug = models.SlugField(max_length=122,default='',unique=True,null=False,verbose_name='Slug Alanı',editable=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = ResearchManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("research:show", kwargs={"slug": self.slug})
    

    def unique_slug(self,new_slug,orjinal_slug,index):
        if Research.objects.filter(slug=new_slug):
            new_slug = '%s-%s'%(orjinal_slug,index)
            index += 1
            return self.unique_slug(new_slug=new_slug,orjinal_slug=orjinal_slug,index=index)
        return new_slug

    def save(self, *args, **kwargs):

        if self.slug == '':
            index=1
            new_slug = slugify(self.title)
            self.slug=self.unique_slug(new_slug=new_slug,orjinal_slug=new_slug,index=index)
            

        super(Research, self).save(*args,**kwargs)


    class Meta:
        ordering = ['-created_at']

researchs/forms.py
from django import forms
from .models import CategoryResearch, Research

class ResearchForm(forms.ModelForm):
    category = forms.ModelChoiceField(queryset=CategoryResearch.objects.all() ,widget=forms.Select(attrs={'class':'ui search dropdown'}))
    class Meta:
        model = Research
        exclude = ('created_at', 'deadline_at')

class CategoryResearchForm(forms.ModelForm):

    class Meta:
        model = CategoryResearch
        fields = '__all__'

researchs/views.py
from django.http.response import HttpResponse, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from .models import Research, CategoryResearch
from .forms import ResearchForm, CategoryResearchForm
from main.decorators import authorized_user
from django.core import serializers
# Create your views here.

@authorized_user
def create(request):
    form = ResearchForm(request.POST or None, request.FILES or None)
    
    if form.is_valid():
        form.save()

        return redirect('research:list')

    return render(request, 'research/create.html', {'form':form})

def list(request):
    categories = CategoryResearch.objects.prefetch_related('researchs').all()

    context = {
        'categories':categories,
        'nbar':'research-list',
    }

    return render(request, 'research/list.html',context)

def show(request, slug):
    research = get_object_or_404(Research ,slug=slug)

    return render(request, 'research/show.html',{'research':research})

def create_category(request):
    form = CategoryResearchForm(request.POST or None)

    if form.is_valid():
        form.save()


    return render(request, 'research/create-category.html', {'form':form})

def get_categories(request):
    data = serializers.serialize('json', CategoryResearch.objects.all())

    #return JsonResponse(data=data, status=200, safe=False) 
    # * Bu işlemi JsonResponse ile yapmak istersem safe=False parametresini eklemem gerekiyor ama HttpResponse ile aşağıdaki gibi yaprsam JS tarafından otomatik olarak JS dict yapısına çevrilmiş olarak bana veriyor.
    return HttpResponse(data, content_type="application/json")

templates/research/create-category.html
{% extends 'base/base.html' %}


{% block title %}
    <h3>Araştırma Kategorisi Ekle</h3>
    <hr>
{% endblock %}

{% block sidebar %}{% endblock %}

{% block content %}

<form method="POST" class="ui form" id="category-form">
    {% csrf_token %}
    <div class="field">
        <label>Kategori Adı</label>
        {{form.category_name}}
    </div>

    <input type="submit" class="ui green button" value="Kaydet" />
</form>

<script>
    $(document).ready(() => {
        $('#category-form').submit(() => {
            parent.$.fancybox.close()
        })
    })
    
</script>

{% endblock %}

{% block lastarticles %}{% endblock %}
{% block footer %}{% endblock %}

templates/research/create.html
{% extends 'base/base.html' %}


{% block title %}
    <h3>Araştırma Ekle</h3>
    <hr>
{% endblock title %}


{% block content %}
    <form class="ui form" method="POST" enctype="multipart/form-data">
        {% if form.errors %}
        <div class="alert alert-danger">
            {{form.errors}}
        </div>
        {% endif %}
        {% csrf_token %}
        {{form.media}}
        {% for field in form %}
        <div class="field">
            <label>{{field.label}}</label>
            {{field}}
        </div>
        {% endfor %}
        <a href="{% url 'research:create-category' %}" class="fancy-add-category">Kategori Ekle</a>
        <input type="submit" value="Oluştur" class="ui button green" />
    </form>

    
{% endblock content %}
    

templates/research/list.html
{% extends 'base/base.html' %}



{% block title %}
    <h3>Araştırmalar</h3> {% if request.user.is_staff or request.user.is_superuser %} <a href="{% url 'research:create' %}" class="ui button green">Araştırma Ekle</a> {% endif %}
    <hr>
{% endblock title %}
    


{% block content %}
    {% for item in categories %}

    {% if item.researchs.get_three_items|length == 0 %}


    {% else %}

    <div align="center">
        <div class="col-6">
            <h3 class="mt-4" style="border-radius:10px; background-color: black;color:white;">{{item.category_name|upper}}</h3>
            <br>
        </div>
        
    
        <div class="row">
            {% for research in item.researchs.get_three_items %}
            <div class="col-4">
                <h4><a href="{% url 'research:show' research.slug %}">{{research.title}}</a></h4>
                <img src="{{research.image.url}}" class="ui medium rounded image" />
            </div>
            {% endfor %}
        </div>
    </div>
    {% endif %}
    {% endfor %}
{% endblock content %}
    

templates/research/show.html
{% extends 'base/base.html' %}

{% block title %}
    <h3>{{research.title}}</h3>
    <hr>
{% endblock %}


{% block content %}
    <div align="center"><img src="{{research.image.url}}" class="ui medium rounded image"></div>
    <hr>
    {{research.content|safe}}
{% endblock %}